server:
  port: 5001

spring:
  application:
    name: turbine-server

turbine:
  app-config: eureka-consumer-ribbon-hystrix
  cluster-name-expression: "default"
  combine-host-port: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password@192.168.0.17:1001/eureka/